language: java
dist: trusty

env:
  - MVN="mvn --settings ${TRAVIS_BUILD_DIR}/.travis.settings.xml"

addons:
  sonarcloud:
    organization: retest
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.sonar/cache/"
    - "${HOME}/.m2/"

install: true

script:
  - ${MVN} clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar

before_deploy:
  # decrypt ReTest secret key
  - openssl aes-256-cbc -K "${encrypted_5faff216b858_key}" -iv "${encrypted_5faff216b858_iv}"
      -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
  # import decrypted ReTest secret key
  - gpg --fast-import retest-gmbh-gpg.asc
  # package and sign artifacts
  - ${MVN} verify -DskipTests -Psign

deploy:
  # deploy artifacts to Maven Central
  - provider: script
    script: ${MVN} deploy -DskipTests -Psign
    on:
      tags: true
